### ISSUE TITLE
Missing license file and headers

### ISSUE THREAD

**Issue by mtreinish** [Qiskit-Partners/qiskit-dell-runtime#1]
The repo doesn't have a license file or license headers in many of the files and these should be added. What is the code licensed under? Per the partner requirements: https://qiskit.org/documentation/partners/requirements.html#code-standards it should be an apache2.0 compatible license.

**Comment by bsantaus** [comment]
Hi! Thanks for catching that - we're on it. I'll close this out when the appropriate changes have been made.

**Comment by bsantaus** [comment]
Ok! I believe I've added the appropriate files and headers. Let me know if I missed anything, but closing this for now.
